### ISSUE TITLE
POL_7 generates ERROR, should be WARN

### ISSUE THREAD

**Issue by maria-messerschmidt** [openpreserve/odf-validator#152] opened 2024-04-16 07:27 UTC
When validating an empty spreadsheet, POL_7 generates an ERROR. It is correct that it should be flagged whenever a spreadsheet is empty since this indicates a possible issue with conversion and should be investigated. But there could be valid reasons for having a random empty spreadsheet, so this should only be WARNING level.

**Comment by dewhattens** [comment] 2024-04-22 10:54
This was by design and hence requires no action.

Close this issue without change.

**Comment by carlwilson** [comment] 2024-05-09 09:27
I'm doing as @dewhattens suggests here, we can discuss if necessary @maria-messerschmidt

**Closed** 2024-07-25 17:21 UTC
Labels: wontfix
